### PR TITLE
issue/517 Fixed missing matches in stdout

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adapt-security/adapt-authoring/issues/517

### Fixed
* Handle outputs without `Error` in stdout.

### CODE REVIEW

**Review by deltanetdan — APPROVED** [review]
👍 fixes the TypeError issue, however AT build still fails as stderr returns Error: read ECONNRESET. Not sure if that should be a seperate issue?

**Comment by oliverfoster** [comment]
Does tom's version work any better? https://github.com/adaptlearning/adapt-cli/pull/164

**Comment by deltanetdan** [comment]
Afraid not, same error in stderr.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
@dancgray could you post the entire error please?

**Comment by KristofferBroberg** [comment]
Tried this and got this error:
[error.txt](https://github.com/adaptlearning/adapt-cli/files/8590730/error.txt)

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
That's very weird. Will have another look.

**Comment by oliverfoster** [comment]
@taylortom i'm not quite sure why this is happening, the code in the adapt-cli seems fine, there's nothing coming out of the stderr 

https://github.com/adaptlearning/adapt-cli/blob/f9acaa56e2f4fd44abd0052f399aa20662ed7f31/lib/integration/AdaptFramework/build.js#L30-L36

**Comment by KristofferBroberg** [comment]
Perhaps @deltanetdan could attach his error output too? I recall getting something else at one point... it´s not unlikely that the error.txt above is due to my installation which is in a somewhat sloppy state.

**Comment by oliverfoster** [comment]
@KristofferBroberg could you try to replicate your issue using the above changes?

**Comment by deltanetdan** [comment]
Apologies @oliverfoster , missed the 1st mention. Console and terminal attached
[issue:517-console.txt](https://github.com/adaptlearning/adapt-cli/files/8762886/issue.517-console.txt)
[issue517-terminal.txt](https://github.com/adaptlearning/adapt-cli/files/8762888/issue517-terminal.txt)

**Comment by deltanetdan** [comment]
I can DM you the .har file if you want?

**Comment by KristofferBroberg** [comment]
> @KristofferBroberg could you try to replicate your issue using the above changes?
> 
> I want to see what's in those stderr and error variable.

Tested:

`  source: null,
  stderr: 'Error: read ECONNRESET\n' +
    '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {\n' +
    '  errno: -54,\n' +
    "  code: 'ECONNRESET',\n" +
    "  syscall: 'read'\n" +
    '}\n' +
    'npm notice \n' +
    'npm notice New minor version of npm available! 8.7.0 -> 8.10.0\n' +
    'npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>\n' +
    'npm notice Run `npm install -g npm@8.10.0` to update!\n' +
    'npm notice \n'`

**Comment by oliverfoster** [comment]
which version of node are you both using?

**Comment by oliverfoster** [comment]
> I can DM you the .har file if you want?

yes please :+1:

**Comment by KristofferBroberg** [comment]
> which version of node are you both using?

16.14.0

**Comment by deltanetdan** [comment]
Node v16.14.2
MongoDB 4.4.10
AT 1.0.0-beta.1 (https://github.com/adapt-security/adapt-authoring)
adapt_framework 5.19.4

**Comment by oliverfoster** [comment]
https://github.com/nodejs/node/issues/42154#issuecomment-1132788918

Could you both upgrade to the latest v16? See if that helps?

**Comment by oliverfoster** [comment]
I'll commit this for the moment and we'll come back to this on another ticket.

**Comment by KristofferBroberg** [comment]
> [nodejs/node#42154 (comment)](https://github.com/nodejs/node/issues/42154#issuecomment-1132788918)
> 
> Could you both upgrade to the latest v16? See if that helps?

No luck!

**Comment by oliverfoster** [comment]
ECONNRESET issue https://github.com/adaptlearning/adapt-cli/issues/169

**Comment by deltanetdan** [comment]
Could you both upgrade to the latest v16? See if that helps?

Also no luck!

**Pull request merged**
