### PR TITLE
Fixes Travis CI Build Fail

### PR DESCRIPTION
**Pull request by hrajotia**
- updated npm modules version

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 (i don't know how to test this)

**Comment by zenduo** [comment]
+1 ditto @oliverfoster

**Comment by moloko** [comment]
Well, as it's now passing the Travis CI built, I guess we'd don't need to check it?

+1

**Comment by oliverfoster** [comment]
+1

**Comment by cajones** [comment]
Hi @oliverfoster do you have an [NPM](https://www.npmjs.com) login? I can add you as collaborator on the adapt-cli package.

**Pull request merged**
