### PR TITLE
Update download module

### LINKED ISSUE #43: possible duplicate grunt in package.json
Hi there, while installing a local version of the cli for development purpose NPM send a warning about duplicate grunt dependency (one in the dependencies and one in the dev-dependencies) I think only the dev dep is needed. 

I'll post a PR removing it if no one react on this issue

### PR DESCRIPTION
**Pull request by hrajotia**
- also have updated the npm dependencies
- fixes #43

### CODE REVIEW

**Comment by taylortom** [comment]
Bear in mind that we were using a fork of download -- have you checked with @cajones that this is ok?

**Comment by hrajotia** [comment]
@taylortom I haven't checked with him yet... but it would be nice if he could share his thoughts here..
I've tested the code with ```node v0.10.40``` on windows machine and its working fine at my end....

**Comment by cajones** [comment]
The fork was due to an out of date version dependency, the author did not update or respond to a PR so we forked to get the CLI working again. If the module is confirmed as working then we can switch back to the original repository.

**Comment by hrajotia** [comment]
@cajones Thanks for letting sharing the background and possibilities :+1:

Additionally the latest version (i.e. v4.4.3) of [download](https://github.com/kevva/download) module contain few dependencies which requires ```node v0.12.0 ```, that's why I've switched back to ```download#3.3.0```.

Today I've also checked above code on MAC (OS X El Capitan) with ```node v0.10.40``` and I could confirm that its working fine there too..

**Comment by taylortom** [comment]
@hrajotia does v3.3.0 work as per @cajones' explanation? (not sure exactly what dependencies broke the package first time around)

**Comment by hrajotia** [comment]
@taylortom - yup the module is working fine by my side, I'm seeking input from people who could test it and provide feedback.. :smile: 

Earlier the ```download#0.1.18``` module was dependent upon ```decompress#0.2.0``` module which was making some problem at our end, please see the PR - https://github.com/kevva/download/pull/17

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
Closing this for https://github.com/adaptlearning/adapt-cli/pull/56

**Pull request closed without merging**
