### PR TITLE
Feature/version check on install

### PR DESCRIPTION
**Pull request by cajones**

### CODE REVIEW

**Comment by cajones** [comment]
Solved a strange issue where tests passed locally but failed when running on Travis-CI.

I believe that it was a test leaking into the context of another.

**Comment by zenduo** [comment]
Hi Chris, whats the easiest way for people to test this?

**Comment by cajones** [comment]
There are six scenarios that were identified...

Given that I have Adapt Framework version 2
When I install a plugin that is tagged as compatible with Adapt V2 framework version
        → Then it should install it.

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `2.0.0`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world`
5. The v2 plugin `hello-world` should install.

When I install a plugin that is tagged with ANY other Adapt framework version
        → Then it should prompt with the Warning

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `2.0.0`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world#v1`
5. The v1 version of hello-world` should prompt with a warning.

When I install a plugin that is NOT tagged at all
        → Then it should prompt with the Warning

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `2.0.0`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world#untagged`
5. The untagged version of hello-world` should prompt with a warning.


Given that I have Adapt Framework version 1.1 or earlier
When I install a plugin that is tagged as compatible with Adapt V1.1 or earlier framework version
        → Then it should install it.

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `1.1.1`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world#v1`
5. The v1 version of hello-world` should install.

When I install a plugin that is tagged with a higher framework version
        → Then it should prompt with the Warning 

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `1.1.1`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world`
5. The v2 version of hello-world` should prompt with a warning.

When I install a plugin that is NOT tagged all
       → Then it should install it.

1. Clone this branch
2. Create a v1 adapt course
3. Edit package.json so the version is `1.1.1`
4. From the course directory `node <path-to-branch>/bin/adapt install hello-world#untagged`
5. The untagged version of hello-world` should install.

These tests are also automated in /test/specs/installing_compatible_plugins_concerns.js and  /test/specs/installing_incompatible_plugins_concerns.js

**Comment by dancgray** [comment]
+1. No problems when run through the test scenarios above.

**Comment by oliverfoster** [comment]
+1 lubsly

**Comment by cajones** [comment]
Thanks

**Pull request merged**
